name: finki-hub-mcp

networks:
  finki_stack:
    driver: bridge
    name: finki_stack
    # Set external to true to use an existing network
    # external: true

services:
  local-mcp:
    environment:
      DATA_STORAGE_URL: ${DATA_STORAGE_URL}
    image: ghcr.io/finki-hub/mcp-local:latest
    networks:
      - finki_stack
    ports:
      - "8808:8808"
    restart: unless-stopped
