name: finki-hub-mcp

services:
  local-mcp:
    image: ghcr.io/finki-hub/mcp-local:latest
    ports:
      - '8808:8808'
    networks:
      - finki_stack
    restart: unless-stopped
    volumes:
      - ./data:/data

networks:
  finki_stack:
    name: finki_stack
    driver: bridge
    # Set external to true to use an existing network
    # external: true
