name: Docker Build (Local MCP)

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'local-mcp/**'
      - '.github/workflows/docker-local-mcp.yaml'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Docker Build (Local MCP)
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:local-mcp'
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/finki-hub/finki-local-mcp:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
